version: '2.1'
volumes:
  collected_static:
services:

  cts-nginx:
    restart: unless-stopped
    build: ./cts_nginx
    image: cts-nginx
    container_name: cts-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - cts-django:uwsgi_django  # Nginx.conf can reference "cts-django" service with the hostname 'uwsgi' or 'cts-django'
      - cts-nodejs:cts_nodejs
    volumes:
      - /var/www/nginx/certs:/etc/nginx/qed # this points to the keys directory
      - /etc/letsencrypt:/etc/letsencrypt  # certs from letsencrypt (uses certbot)
    volumes_from:
      - cts-django:ro  # Mount all volumes from "cts-django" to NGINX, so it can access the collected static files

  # CTS Django front-end
  cts-django:
    restart: unless-stopped
    build: ./cts_app
    image: cts-django
    container_name: cts-django
    expose:
      - "8080"
    volumes:
      - collected_static:/src/collected_static
      - .:/src
      # - /var/www/app_data:/src/app-data
    environment:
      - REDIS_HOSTNAME=cts-redis
    links:
      - cts-redis
      - cts-mongodb

 # Redis (message broker)
  cts-redis:
    restart: unless-stopped
    build: ./cts_redis
    image: cts-redis
    container_name: cts-redis
    expose:
      - "6379"

  # CTS nodejs submodule
  cts-nodejs:
    restart: unless-stopped
    build: ./cts_nodejs
    image: cts-nodejs
    container_name: cts-nodejs
    expose:
      - "4000"
    environment:
      - NODEJS_HOST=cts_nodejs
      - NODEJS_PORT=4000
      - REDIS_HOSTNAME=cts-redis
      - REDIS_PORT=6379
    links:
      - cts-redis
    # volumes:
    #   - ./cts_nodejs:/src

  # Celery worker - manager calc
  cts-celery-worker:
    restart: unless-stopped
    build: ./cts_celery
    image: cts-celery
    container_name: cts-celery
    command: celery -A tasks worker -Q manager_queue -l info -n manager_worker -c 1
    links:
      - cts-redis
    environment:
      - REDIS_HOSTNAME=cts-redis
    volumes:
      - ./cts_celery:/src

  # # Celery worker - cts calc
  cts-celery-manager:
    restart: unless-stopped
    build: ./cts_celery
    image: cts-celery
    container_name: cts-celery
    command: celery -A tasks worker -Q cts_queue -l info -n cts_worker -c 2
    links:
      - cts-redis
    environment:
      - REDIS_HOSTNAME=cts-redis
    volumes:
      - ./cts_celery:/src

  # mongoDB database container
  cts-mongodb:
    restart: unless-stopped
    build: ./cts_mongodb
    image: cts-mongodb
    container_name: cts-mongodb
    volumes:
      - /var/www/mongodb:/data/db
    expose:
      - "27017"

  # Apache Tomcat container
  cts-tomcat:
    restart: unless-stopped
    build: ./cts_tomcat
    image: cts-tomcat
    container_name: cts-tomcat
    expose:
      - "8080"
    environment:
      - JAVA_OPTS=-Xmx1g
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    volumes:
      - ./cts_tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./cts_tomcat/webapps:/usr/local/tomcat/webapps
      - ./cts_tomcat/chemaxon/licenses:/home/tomcat/.chemaxon/licenses
