apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cts-mongodb
  name: cts-mongodb
  namespace: qed-45-stg
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cts-mongodb
  serviceName: cts-mongodb
  template:
    metadata:
      labels:
        app: cts-mongodb
    spec:
      containers:
      - image: registry.epa.gov/qed/cts_kube/cts-mongodb:dev-gl
        imagePullPolicy: Always
        command:
          - mongod
          - --dbpath
          - '/data/db/cts'
          - --bind_ip_all
        name: cts-mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db/cts
          name: cts-mongodb-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      imagePullSecrets:
        - name: glcr-auth
      volumes:
      - name: cts-mongodb-data
        persistentVolumeClaim:
          claimName: cts-mongodb-pvc
