apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cts-mongodb
  name: cts-mongodb
  namespace: qed-kube-dev
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cts-mongodb
  serviceName: cts-mongodb
  template:
    metadata:
      labels:
        app: cts-mongodb
    spec:
      containers:
      - image: ghcr.io/quanted/cts-mongodb:dev-kube
        imagePullPolicy: Always
      # - image: cts-mongodb
      #   imagePullPolicy: Never
        command:
          - mongod
          - --dbpath
          - '/data/db/cts'
          - --bind_ip_all
        name: cts-mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: cts-mongodb-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: cts-mongodb-data
        persistentVolumeClaim:
          claimName: cts-mongodb-pvc
