apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cts-nginx
  name: cts-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cts-nginx
    spec:
      containers:
        - image: ghcr.io/quanted/cts-nginx:dev-kube
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /src/collected_static
            # - mountPath: /src/cts_app/static/cts_app
              name: collected-static
      restartPolicy: Always
      volumes:
        - name: collected-static
          hostPath:
            # NOTE Docker Deskop 3.5.2 / Kubernetes v1.21.2 / WSLv2 mount on Windows 10:
            # path: /run/desktop/mnt/host/c/Users/inick/GitHub/cts_kube/cts_app/static/cts_app
            path: /run/desktop/mnt/host/c/Users/inick/GitHub/cts_kube/cts_app/collected_static
#      volumes:
#        - name: collected-static
#          persistentVolumeClaim:
#            claimName: collected-static-pvolume-claim1