apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: cts-nodejs
  name: cts-nodejs
  #namespace: qed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-nodejs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cts-nodejs
    spec:
      containers:
      - env:
        - name: NODEJS_HOST
          value: cts_nodejs
        - name: NODEJS_PORT
          value: "4000"
        - name: REDIS_HOSTNAME
          value: redis
        - name: REDIS_PORT
          value: "6379"
        image: ghcr.io/quanted/cts-nodejs:dev-kube
        imagePullPolicy: Always
        name: cts-nodejs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
