apiVersion: v1
kind: Service
metadata:
  name: cts-nginx
spec:
  selector:
    app: cts-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31002
      name: http
  type: NodePort