apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cts-django
  name: cts-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-django
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cts-django
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: cts-config
        image: ghcr.io/quanted/cts_app:dev-kube
        imagePullPolicy: Always
        name: cts-django
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /src/cts_app/collected_static
          name: collected-static
        - mountPath: /src/app-data
          name: app-data
        - mountPath: /src/cts_app
          name: django-code
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name: collected-static
          hostPath:
            path: /host/collected-static
        - name: app-data
          hostPath:
            path: /host/app-data
        - name: django-code
          hostPath:
            path: /host/django-code
#      volumes:
#      - name: collected-static
#        persistentVolumeClaim:
#          claimName: collected-static-pvolume-claim1
#      - name: app-data
#        persistentVolumeClaim:
#          claimName: app-data-pvolume-claim1
