apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cts-biotransformer
  name: cts-biotransformer
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-biotransformer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cts-biotransformer
    spec:
      containers:
        - name: cts-biotransformer
          env:
          - name: BT_JAR_PATH
            value: /src/biotransformer3.0jar
          image: ghcr.io/quanted/cts-biotransformer:dev
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            exec:
              command:
                - ls
                - /
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - ls
                - /
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
          - containerPort: 5002
            protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
