# apiVersion: v1
# kind: Service
# metadata:
#   name: cts-operaws
#   namespace: qed-45-stg
# spec:
#   ports:
#   - port: 3344
#     protocol: TCP
#     targetPort: 3344
#   selector:
#     app: cts-operaws
#   type: ClusterIP
