apiVersion: v1
kind: ConfigMap
metadata:
  name: cts-config
  labels:
    app: cts-config
data:
  IN_DOCKER: "True"
  # DASK_SCHEDULER: "cts-dask-scheduler:8786"
  DJANGO_SETTINGS_MODULE: "settings"
  # MONGO_SERVER: "cts-mongodb:27017"
  SECRET_KEY: "wx$p52y!1p!*p$$y^d1!f9@5=)3o#88+08-i9_mc8*-8h+x2&@w"
  UBERTOOL_REST_SERVER: "http://cts-nginx:7777"
  #UBERTOOL_REST_SERVER: "qed-dev.edap-cluster.com/nta/flask_proxy"
  # POSTGRES_HOST: "qedaurorastack-databaseb269d8bb-1dy6l8bdz01k1.cluster-ro-crqjwmaelnsw.us-east-1.rds.amazonaws.com"
  # POSTGRES_PORT: "3306"
  # POSTGRES_DB: "ms2_db"
  # POSTGRES_USER: "qedadmin"
