apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cts-redis
  name: cts-redis
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cts-redis
    spec:
      containers:
      - image: ghcr.io/quanted/cts-redis:dev-kube
        imagePullPolicy: Always
      # - image: cts-redis
      #   imagePullPolicy: Never
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        name: cts-redis
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 30
        ports:
        - containerPort: 6379
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler