apiVersion: v1
kind: Service
metadata:
  name: cts-ctsws
  namespace: qed-kube-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cts-ctsws
  type: ClusterIP