apiVersion: v1
kind: ConfigMap
metadata:
  name: cts-config
  namespace: qed-45-stg
  labels:
    app: cts-config
data:
  CTS_BIOTRANS_SERVER: '${CTS_BIOTRANS_SERVER}' 
  CTS_DB_HOST: mongodb://cts-mongodb:27017
  CTS_DB_NAME: cts
  CTS_EFS_SERVER: http://cts-tomcat:8080
  CTS_EMAIL: '${CTS_EMAIL}'
  # CTS_EMAIL_PASS: '${CTS_EMAIL_PASS}'
  CTS_EMAIL_RECIPIENT: '${CTS_EMAIL_RECIPIENT}'
  CTS_ENVIPATH_SERVER: '${CTS_ENVIPATH_SERVER}'
  CTS_EPI_SERVER: '${CTS_EPI_SERVER}'
  CTS_JCHEM_SERVER: http://cts-tomcat:8080
  CTS_MEASURED_SERVER: '${CTS_MEASURED_SERVER}'
  CTS_OPERA_SERVER: '${CTS_OPERA_SERVER}'
  CTS_REST_SERVER: '${CTS_REST_SERVER}'
  CTS_TEST_SERVER: https://comptox.epa.gov/dashboard/web-test
  CTS_VERSION: '${CTS_VERSION}'
  CTS_RECAPTCHA_KEY: '${CTS_RECAPTCHA_KEY}'
  CTS_TOMCAT_PASS: '${CTS_TOMCAT_PASS}'
  CTS_TOMCAT_USER: |
    <?xml version='1.0' encoding='utf-8'?>
    <tomcat-users>
      <role rolename="manager-gui"/>
      <user username="docker" password="${CTS_TOMCAT_PASS}" roles="manager-gui"/>
    </tomcat-users>
  DJANGO_SETTINGS_MODULE: "settings"
  ENV_NAME: kube_dev
  MARVIN_PROXY: '${MARVIN_PROXY}'
  NODEJS_HOST: cts-nodejs
  NODEJS_PORT: "4000"
  PASSWORD_REQUIRED: "False"
  REDIS_HOSTNAME: cts-redis
  REDIS_PORT: "6379"
