apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: cts-worker
  name: cts-worker
  #namespace: qed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cts-worker
    spec:
      containers:
      - args:
        - celery
        - worker
        - -A
        - tasks
        - -Q
        - cts_queue
        - -l
        - info
        - -n
        - cts_worker
        - -c
        - "2"
        env:
        - name: DOCKER_HOSTNAME
          value: QED_KUBERNETES
        - name: REDIS_HOSTNAME
          value: redis
        image: quanted/cts_celery:dev
        imagePullPolicy: Always
        name: worker-cts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
