apiVersion: v1
kind: ConfigMap
metadata:
  name: cts-config
  namespace: qed-kube-dev
  labels:
    app: cts-config
data:
  CTS_BIOTRANS_SERVER: http://cts-biotransformer:5002
  CTS_CHEMAXON_LICENSE: '${CTS_CHEMAXON_LICENSE}'
  CTS_DB_HOST: mongodb://cts-mongodb:27017
  CTS_DB_NAME: cts
  CTS_EFS_SERVER: http://cts-ctsws:8080
  CTS_EMAIL: ctsemailserver@gmail.com
  CTS_EMAIL_RECIPIENTS: ctsemailserver@gmail.com
  CTS_ENVIPATH_SERVER: http://cts-envipath:5003
  CTS_EPI_SERVER: https://ceamdev.ceeopdev.net/epi/estimated
  CTS_JCHEM_SERVER: http://cts-jchemws:8080
  CTS_MEASURED_SERVER: https://ceamdev.ceeopdev.net/epi/measured
  CTS_OPERA_SERVER: https://ceamdev.ceeopdev.net/operaws
  CTS_REST_SERVER: https://qedcloud.net
  CTS_TEST_SERVER: https://comptox.epa.gov/dashboard/web-test
  CTS_VERSION: "1.3.3"
  CTS_EMAIL_PASS: "${CTS_EMAIL_PASS}"
  CTS_RECAPTCHA_KEY: "${CTS_RECAPTCHA_KEY}"
  CTS_STATIC_URL: "/cts/static/"
  CTS_TOMCAT_PASS: "${CTS_TOMCAT_PASS}"
  CTS_TOMCAT_USER: |
    <?xml version='1.0' encoding='utf-8'?>
    <tomcat-users>
      <role rolename="manager-gui"/>
      <user username="docker" password="${CTS_TOMCAT_PASS}" roles="manager-gui"/>
    </tomcat-users>
  DJANGO_SETTINGS_MODULE: "settings"
  ENV_NAME: kube_dev
  MARVIN_PROXY: http://172.17.0.1
  MONGO_SERVER: "cts-mongodb:27017"
  NODEJS_HOST: https://qedcloud.net
  NODEJS_PORT: "80"
  PASSWORD_REQUIRED: "False"
  REDIS_HOSTNAME: cts-redis
  REDIS_PORT: "6379"
