apiVersion: v1
kind: ConfigMap
metadata:
  name: cts-config
  namespace: cts-kube
  labels:
    app: cts-config
data:
  CTS_BIOTRANS_SERVER: http://cts-biotransformer:5002
  CTS_DB_HOST: mongodb://mongodb:27017
  CTS_DB_NAME: cts
  CTS_EFS_SERVER: http://cts-tomcat:8080
  CTS_EMAIL: ctsemailserver@gmail.com
  CTS_EMAIL_RECIPIENT: ctsemailserver@gmail.com
  CTS_ENVIPATH_SERVER: http://cts-envipath:5003
<<<<<<< Updated upstream
  CTS_EPI_SERVER: http://172.17.0.1:55342/rest/episuite/estimated
  CTS_JCHEM_SERVER: http://cts-tomcat:8080
  CTS_MEASURED_SERVER: http://172.17.0.1:55342/rest/episuite/measured
  CTS_OPERA_SERVER: http://cts-operaws:3344
  CTS_REST_SERVER: http://host.docker.internal
=======
  CTS_EPI_SERVER: http://localhost:30002/epi/estimated
  CTS_JCHEM_SERVER: http://cts-jchemws:8080
  CTS_MEASURED_SERVER: http://localhost:30002/epi/measured
  CTS_MOLGPKA_SERVER: http://cts-nginx
  CTS_OPERA_SERVER: http://cts-operaws:3344
  CTS_PKASOLVER_SERVER: http://cts-nginx
  CTS_RECAPTCHA_KEY: '${CTS_RECAPTCHA_KEY}'
  CTS_REST_SERVER: http://localhost:30002
  CTS_STATIC_URL: '/cts/static/'
>>>>>>> Stashed changes
  CTS_TEST_SERVER: https://comptox.epa.gov/dashboard/web-test
  CTS_SPARC_SERVER: http://204.46.160.69:8080
  CTS_VERSION: "1.2"
  DJANGO_SETTINGS_MODULE: "settings"
<<<<<<< Updated upstream
  ENV_NAME: local_docker_dev
  MARVIN_PROXY: http://172.17.0.1
  MONGO_SERVER: "cts-mongodb:27017"
  NODEJS_HOST: nginx
  NODEJS_PORT: "4000"
=======
  # ENV_NAME: kube_dev
  MARVIN_PROXY: http://localhost:30002
  MONGO_SERVER: "cts-mongodb:27017"
  NODEJS_HOST: http://localhost:30002
  NODEJS_PORT: "80"
>>>>>>> Stashed changes
  PASSWORD_REQUIRED: "False"
  REDIS_HOSTNAME: redis
  REDIS_PORT: "6379"
