# apiVersion: v1
# kind: Service
# metadata:
#   name: cts-biotransformer
#   namespace: qed-kube-dev
# spec:
#   ports:
#   - port: 5002
#     protocol: TCP
#     targetPort: 5002
#   selector:
#     app: cts-biotransformer
#   type: ClusterIP
