apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cts-manager
  name: cts-manager
  namespace: cts-kube
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cts-manager
    spec:
      containers:
      - command:
        - celery
        - -A
        - tasks
        - worker
        - -Q
        - manager_queue
        - -l
        - info
        - -n
        - manager_worker
        - -c
        - "1"
        env:
        - name: DOCKER_HOSTNAME
          value: QED_KUBERNETES
        - name: REDIS_HOSTNAME
          value: redis
        image: registry.epa.gov/qed/cyanweb_kube/cts-celery:dev-gl
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cts-config
        livenessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        name: worker-cts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
