apiVersion: v1
kind: Service
metadata:
  name: cts-django
  namespace: qed-45-stg
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cts-django
  type: ClusterIP
