apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cts-tomcat
  name: cts-tomcat
  namespace: qed-45-stg
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-tomcat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cts-tomcat
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx1024m
        image: registry.epa.gov/qed/cyanweb_kube/cts-tomcat:dev-gl
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        name: cts-tomcat
        ports:
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
          - mountPath: /usr/local/tomcat/conf/tomcat-users.xml
            name: cts-tomcat-user
          - mountPath: /home/tomcat/.chemaxon/licenses
            name: cts-tomcat-chemaxon
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name: cts-tomcat-chemaxon
        persistentVolumeClaim:
          claimName: cts-chemaxon-license-pvc
        - name: cts-tomcat-user
        persistentVolumeClaim:
          claimName: cts-tomcat-user-pvolume-claim1
