apiVersion: v1
kind: ConfigMap
metadata:
  name: cts-config
  labels:
    app: cts-config
data:
  CTS_BIOTRANS_SERVER: http://biotransformer:5002
  CTS_DB_HOST: mongodb://mongodb:27017
  CTS_DB_NAME: cts
  CTS_EFS_SERVER: http://qed-tomcat:8080
  CTS_EMAIL: ctsemailserver@gmail.com
  CTS_EMAIL_RECIPIENT: ctsemailserver@gmail.com
  CTS_EPI_SERVER: http://172.29.128.1:55342/rest/episuite/estimated
  CTS_JCHEM_SERVER: http://qed-tomcat:8080
  CTS_MEASURED_SERVER: http://host.docker.internal:55342/rest/episuite/measured
  CTS_OPERA_SERVER: http://operaws:3344
  CTS_REST_SERVER: http://host.docker.internal
  CTS_TEST_SERVER: https://comptox.epa.gov/dashboard/web-test
  CTS_SPARC_SERVER: http://204.46.160.69:8080
  CTS_VERSION: "1.2"
  DJANGO_SETTINGS_FILE: settings_docker
  DJANGO_SETTINGS_MODULE: "settings"
  ENV_NAME: local_docker_dev
  EPA_ACCESS_TEST_URL: http://134.67.114.2
  IN_DOCKER: "True"
  IN_PROD: "0"
  IS_AWS: "False"
  IS_PUBLIC: "False"
  MARVIN_PROXY: http://host.docker.internal
  MONGO_SERVER: "cts-mongodb:27017"
  NODEJS_HOST: nginx
  NODEJS_PORT: "4000"
  PASSWORD_REQUIRED: "False"
  REDIS_HOSTNAME: redis
  REDIS_PORT: "6379"
  SECRET_KEY: "wx$p52y!1p!*p$$y^d1!f9@5=)3o#88+08-i9_mc8*-8h+x2&@w"
  UBERTOOL_REST_SERVER: http://cts-nginx:7777
