apiVersion: v1
kind: Service
metadata:
  name: cts-nodejs
  namespace: qed-45-stg
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: cts-nodejs
  type: ClusterIP
