apiVersion: v1
kind: Service
metadata:
  name: cts-envipath
  namespace: cuts-kube
spec:
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    app: cts-envipath
  type: ClusterIP
