apiVersion: v1
kind: Service
metadata:
  name: cts-envipath
  namespace: qed-kube-dev
spec:
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    app: cts-envipath
  type: ClusterIP
