apiVersion: v1
kind: Service
metadata:
  name: cts-nginx
  namespace: qed-45-stg
spec:
  selector:
    app: cts-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
