apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cts-tomcat
  name: cts-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-tomcat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cts-tomcat
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          # value: -Xmx512m
          value: -Xmx1024m
        image: ghcr.io/quanted/cts-tomcat:dev-kube
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            # memory: "256Mi"
            # cpu: "250m"
            memory: "512Mi"
            cpu: "500m"
          limits:
            # memory: "512Mi"
            # cpu: "500m"
            memory: "1024Mi"
            cpu: "1000m"
        name: cts-tomcat
        ports:
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
          - mountPath: /usr/local/tomcat/webapps
            name: cts-tomcat-webapps
          - mountPath: /usr/local/tomcat/conf/tomcat-users.xml
            name: cts-tomcat-user
          - mountPath: /home/tomcat/.chemaxon/licenses
            name: cts-tomcat-chemaxon
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name: cts-tomcat-webapps
          hostPath:
            path: /run/desktop/mnt/host/c/Users/inick/GitHub/cts_kube/cts_tomcat/webapps
        - name: cts-tomcat-user
          hostPath:
            path: /run/desktop/mnt/host/c/Users/inick/GitHub/cts_kube/cts_tomcat/tomcat-users.xml
        - name: cts-tomcat-chemaxon
          hostPath:
            path: /run/desktop/mnt/host/c/Users/inick/GitHub/cts_kube/cts_tomcat/chemaxon/licenses
      # - name: cts-tomcat-config
      #   persistentVolumeClaim:
      #     claimName: cts-tomcat-config-pvolume-claim1
      
