apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cts-operaws
  name: cts-operaws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cts-operaws
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cts-operaws
    spec:
      containers:
        - name: cts-operaws
          image: ghcr.io/quanted/operaws:dev-kube
          imagePullPolicy: Always
          ports:
          - containerPort: 3344
            protocol: TCP
          volumeMounts:
            - mountPath: /src/operaws
              name: operaws-code
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name: operaws-code
          hostPath:
            path: /run/desktop/mnt/host/c/Users/inick/GitHub/OPERAWS
