apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      # - image: registry.epa.gov/qed/qed-kube/redis:dev
      - image: redis:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        name: redis
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 30
        ports:
        - containerPort: 6379
          protocol: TCP
        # volumeMounts:
        # - mountPath: /etc/redis/database
        #   name: redis-pvolume
      imagePullSecrets:
        - name: glcr-auth
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      # volumes:
      # - name: redis-pvolume
      #   persistentVolumeClaim:
      #     claimName: redis-pvolume-claim1
